services:
  cranedev:
    image: michaelsauter/golang:1.7
    rm: true
    interactive: true
    tty: true
    volume: ["$GOPATH:/go"]
    workdir: /go/src/github.com/michaelsauter/crane
    command: ["sh"]

mac-syncs:
  "$GOPATH:/go":
    uid: 1000
    gid: 1000
    autostart: true
